In [1]:
import pandas as pd

In [2]:
melb_data = pd.read_csv('data/melb_data_ps.csv', sep=',')
melb_df = melb_data.copy()
melb_df.head()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,"-37.8072, 144.9941"

### Задание 2.3 (External resource)

Напишите функцию **delete_columns(df, col=[ ])**, которая удаляет столбцы из DataFrame и возвращает новую таблицу. Если одного из указанных столбцов не существует в таблице, то функция должна возвращать None.

Пример **DataFrame**:

In [3]:
customer_df = pd.DataFrame({
            'number': [0, 1, 2, 3, 4],
            'cust_id': [128, 1201, 9832, 4392, 7472],
            'cust_age': [13, 21, 19, 21, 60],
            'cust_sale': [0, 0, 0.2, 0.15, 0.3],
            'cust_year_birth': [2008, 2000, 2002, 2000, 1961],
            'cust_order': [1400, 14142, 900, 1240, 8430]
        })
# Просмотр нашей таблицы
display(customer_df)

# Функция удаления заданных столбцов
def delete_columns(df, col=[]):
    # Пройдёмся циклом по списку столбцов
    for i in col:
        # Если столбца нету в нашей таблице
        if i not in df.columns:
            # Возвращаем None
            return None
    # Удаляем заданные столбцы из нашей таблицы методом .drop() 
    # а в качестве аргумента передаём столбцы 
    # и указываем ось (axis=1) по вертикали(по столбцам)
    return df.drop(col, axis=1)
display(delete_columns(customer_df, col=['number', 'cust_age']))

   number  cust_id  cust_age  cust_sale  cust_year_birth  cust_order
0       0      128        13       0.00             2008        1400
1       1     1201        21       0.00             2000       14142
2       2     9832        19       0.20             2002         900
3       3     4392        21       0.15             2000        1240
4       4     7472        60       0.30             1961        8430

   cust_id  cust_sale  cust_year_birth  cust_order
0      128       0.00             2008        1400
1     1201       0.00             2000       14142
2     9832       0.20             2002         900
3     4392       0.15             2000        1240
4     7472       0.30             1961        8430

### Задание 2.4

Задан DataFrame ***countries_df***, содержащий следующие столбцы: название страны, население (*population*) в миллионах человек и площадь страны (*area*) в квадратных километрах.

Для каждой страны рассчитайте плотность населения (количество человек на квадратный километр).

Затем по полученным данным рассчитайте среднее по плотностям населения в указанных странах. Ответ **округлите до сотых**.

*Плотность населения рассчитывается как количество человек, проживающих на территории отдельной страны, делённое на площадь этой страны. Обратите внимание, что население в таблице представлено в миллионах.*

In [4]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})
# Плотность населения (количество человек(указанные в миллионах) на квадратный километр)
population_density = countries_df['population']/countries_df['area']*1000000
# Среднее по плотностям населения в указанных странах (округлённое до сотых)
population_mean = round(population_density.mean(), 2)
population_mean

np.float64(84.93)

In [56]:
display(melb_df['Address'])

0            85 Turner St
1         25 Bloomburg St
2            5 Charles St
3        40 Federation La
4             55a Park St
               ...
13575        12 Strada Cr
13576       77 Merrett Dr
13577         83 Power St
13578        96 Verdon St
13579          6 Agnes St
Name: Address, Length: 13580, dtype: object

In [6]:
def get_street_type(adress):
    exclude_list = ['N', 'S', 'E', 'W']
    addres_list = adress.split(' ')
    street_type = addres_list[-1]
    if street_type in exclude_list:
        street_type = addres_list[-2]
    return street_type

In [ ]:
street_types = melb_df['Address'].apply(get_street_type)
display(street_types.value_counts())

In [51]:
popular_streets = street_types.value_counts().nlargest(10).index
display(popular_streets)

Index(['St', 'Rd', 'Ct', 'Dr', 'Av', 'Gr', 'Pde', 'Pl', 'Cr', 'Cl'], dtype='object', name='Address')

In [52]:
melb_df['StreetType'] = street_types.apply(lambda x: x if x in popular_streets else 'other')