# Обработки Категориальных Признаков

## Label Encoding (Порядковое кодирование)

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
# Создадим пример DataFrame
data = {'цвет': ['красный', 'синий', 'зеленый', 'красный', 'синий', "желтый"]}
df = pd.DataFrame(data)
df

      цвет
0  красный
1    синий
2  зеленый
3  красный
4    синий
5   желтый

In [ ]:
# Создадим экземпляр LabelEncoder
label_encoder = LabelEncoder()

# Обучим LabelEncoder на столбце 'цвет' и преобразуем его
df['цвет_encoded'] = label_encoder.fit_transform(df['цвет'])

print(df)

## One-Hot Encoding (Однократное кодирование)

In [13]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [16]:
# Создадим пример DataFrame
data = {'цвет': ['красный', 'синий', 'зеленый', 'красный', 'синий', "желтый"]}
df = pd.DataFrame(data)
df

      цвет
0  красный
1    синий
2  зеленый
3  красный
4    синий
5   желтый

In [ ]:
# Создадим экземпляр OneHotEncoder
# sparse=False для возврата numpy массива, а не sparse matrix,
# handle_unknown='ignore' обрабатывает неизвестные категории,которые могут появится позже
# drop='first' удаляет один столбец для избежания мультиколлинеарности
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='first') # , drop='first')

# Обучим OneHotEncoder на столбце 'цвет' и преобразуем данные
ft= encoder.fit_transform(df[['цвет']])

# Создадим DataFrame из результатов One-Hot Encoding
onehot_df = pd.DataFrame(ft, columns=encoder.get_feature_names_out(['цвет']))

# Объединим исходный DataFrame с One-Hot Encoding
df = pd.concat([df, onehot_df], axis=1)
print(df)

# Удалим исходный столбец 'цвет'
df = df.drop('цвет', axis=1)

print(df)

      цвет  цвет_зеленый  цвет_красный  цвет_синий
0  красный           0.0           1.0         0.0
1    синий           0.0           0.0         1.0
2  зеленый           1.0           0.0         0.0
3  красный           0.0           1.0         0.0
4    синий           0.0           0.0         1.0
5   желтый           0.0           0.0         0.0
   цвет_зеленый  цвет_красный  цвет_синий
0           0.0           1.0         0.0
1           0.0           0.0         1.0
2           1.0           0.0         0.0
3           0.0           1.0         0.0
4           0.0           0.0         1.0
5           0.0           0.0         0.0

OneHotEncoder намеренно возвращает float, чтобы обеспечить совместимость с широким спектром алгоритмов машинного обучения.

В большинстве случаев лучше оставить их как float, чтобы избежать потенциальных проблем с интерпретацией признаков алгоритмами машинного обучения

преобразовать в int можно например, для экономии памяти

In [ ]:
import numpy as np

In [ ]:
# можем перевести в (int) или (np.int8)

df = df.astype(np.int8)

### способ Dummy Variable Encoding

In [24]:
import pandas as pd

In [32]:
# Создадим пример DataFrame
data = {'цвет': ['красный', 'синий', 'зеленый', 'красный', 'синий', "желтый"]}
df = pd.DataFrame(data)
df

      цвет
0  красный
1    синий
2  зеленый
3  красный
4    синий
5   желтый

In [33]:
# Dummy Variable Encoding с использованием pandas get_dummies()
df_dummy = pd.get_dummies(df, columns=['цвет'])

In [34]:
df_dummy

   цвет_желтый  цвет_зеленый  цвет_красный  цвет_синий
0        False         False          True       False
1        False         False         False        True
2        False          True         False       False
3        False         False          True       False
4        False         False         False        True
5         True         False         False       False

Большинство алгоритмов машинного обучения корректно обрабатывают булевы значения как бинарные числовые значения.т.к. False и True уже представляют собой бинарные значения (0 и 1). False эквивалентно 0, а True эквивалентно 1